Repository fga-eps-mds/2022-2-Alectrion-FrontEnd, pull requests merged in 2023-01, with the labels that each got.

#4 Foram alteradas as configurações de usuário.
  src/components/NavBar/index.tsx
  src/components/User-Tables/index.test.tsx
  src/components/User-Tables/index.tsx
  src/components/edit-user-form/index.tsx
  src/pages/task/index.tsx
  src/pages/user-screen/index.tsx
  yarn.lock
Labels: MDS, US

#5 Us/02 sessão de usuário
  .env.example
  src/App.tsx
  src/components/Equipament-Tables/index.tsx
  src/components/NavBar/index.tsx
  src/components/User-Tables/index.tsx
  src/components/edit-button/index.tsx
  src/components/edit-user-form/index.tsx
  src/pages/task/index.tsx
  src/pages/user-screen/index.tsx
Labels: bug, MDS

#2 Us/06 cadastro equipamentos
  src/components/Equipament-Tables/index.tsx
  src/components/Equipament-Tables/style.tsx
  src/components/filter-order-service/index.tsx
  src/components/order-services-table/index.tsx
  src/components/register-equip-form/index.tsx
  src/components/register-order-service-form/index.tsx
  src/pages/ScreenEquipaments/index.tsx
  src/pages/order-service/index.test.tsx
  src/pages/order-service/index.tsx
  src/pages/order-services/index.tsx
Labels: MDS, US

#25 US 12: Termos
  package.json
  src/components/Movimentation/index.tsx
  src/components/Term/assets/brasao.png
  src/components/Term/css-reset.css
  src/components/Term/html2pdf.d.ts
  src/components/Term/index.tsx
  src/components/Term/styles.css
  src/components/TermModal/index.tsx
  src/components/TermModal/styles.css
  src/components/gerar-termo/index.tsx
  src/utils/types.ts
  yarn.lock
Labels: US

#21 Us/07 cadastro de ordem de serviço
  src/components/edit-os-button/index.tsx
  src/components/edit-os-button/styles.tsx
  src/components/order-service-update-form/index.tsx
  src/components/order-service-update-form/styles.tsx
  src/components/order-services-table/index.tsx
  src/components/register-order-service-form/index.tsx
  src/pages/order-service-register/index.test.tsx
  src/pages/order-service-register/index.tsx
  src/pages/order-service-update/index.tsx
  src/pages/order-service/index.tsx
  src/pages/order-services/index.test.tsx
  src/pages/order-services/index.tsx
  src/routes/routes.tsx
Labels: US
